### PR TITLE
Scratch app with nativescript angular.

### PR DESCRIPTION
**Pull request by mmahmoodictbd**
Remove app with typescript.

### CODE REVIEW

**Comment by imtiaz-emu** [comment]
@mmahmoodictbd We need to remove `node_modules/` from the repository. As it contains dependency  libraries and can be generated on local machine. So, we don't need this to be pushed, it'll create conflict on other user's machine.

**Comment by mmahmoodictbd** [comment]
> @mmahmoodictbd We need to remove `node_modules/` from the repository. As it contains dependency libraries and can be generated on local machine. So, we don't need this to be pushed, it'll create conflict on other user's machine.

Good catch! Removed.

**Comment by hnjaman** [comment]
node modules is very dangerous dir. It can ruin any developers day.

**Review by hnjaman — COMMENTED** [review]
now its good to maintain the repository changes

**Pull request merged**
